// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5kDGy8Xcb2SP_iYGURw56cxLKpQE5Yyo',
    appId: '1:198501208363:web:08ee43b5a7dc2e9ad4356e',
    messagingSenderId: '198501208363',
    projectId: 'farmereats-2c68c',
    authDomain: 'farmereats-2c68c.firebaseapp.com',
    storageBucket: 'farmereats-2c68c.appspot.com',
    measurementId: 'G-7KS1HR93XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCreNS5Kaxd6mKFRTKGlUatvJy6OfS1SSs',
    appId: '1:198501208363:android:e84823e33a26cb25d4356e',
    messagingSenderId: '198501208363',
    projectId: 'farmereats-2c68c',
    storageBucket: 'farmereats-2c68c.appspot.com',
  );
}
